name: Restart Hugging Face Space

on:
  schedule:
    - cron: '*/10 * * * *' # Schedule runs every 10 minutes

jobs:
  restart-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Restart Hugging Face Space
        run: python restart_space.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
